import Footer from "./footer"
import NavBar from "./navbar"
import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <NavBar />
          <div className="child">
            {children}
          </div>

          <Footer />
        </main>
      </body>
    </html>
  )
}
